In [2]:
import pandas as pd
import os

In [3]:
os.chdir(r"C:/Projects/Model Drifting and Data Monitoring")

In [4]:
import os
print(f"Current Working Directory: {os.getcwd()}")

Current Working Directory: C:\Projects\Model Drifting and Data Monitoring

In [5]:
tdf = pd.read_csv("data/train.csv")

In [6]:
tdf.describe()

             age        income  credit_score
count   5.000000      5.000000      5.000000
mean   35.200000  50000.000000    700.000000
std     9.934787  20310.096012     38.078866
min    25.000000  30000.000000    650.000000
25%    29.000000  35000.000000    680.000000
50%    32.000000  45000.000000    700.000000
75%    40.000000  60000.000000    720.000000
max    50.000000  80000.000000    750.000000

In [7]:
ndf = pd.read_csv("data/new_data.csv")

In [8]:
ndf.describe()

             age        income  credit_score
count   5.000000      5.000000       5.00000
mean   36.600000  51000.000000     705.00000
std     8.443933  18867.962264      31.22499
min    27.000000  32000.000000     660.00000
25%    31.000000  36000.000000     690.00000
50%    35.000000  48000.000000     710.00000
75%    42.000000  61000.000000     725.00000
max    48.000000  78000.000000     740.00000